<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_input_fullname</name>
   <tag></tag>
   <elementGuidId>ce01bb20-683b-419d-b14f-b1086be158f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31d12b8e-8261-4b98-8da5-7db07117877e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fec0506-5924-48d8-911b-e80b448c98df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6d12f89b-23a7-4221-9649-5e524fc08345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAddress</value>
      <webElementGuid>c2006bc3-2886-46ae-8537-e1abb2b05ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap</value>
      <webElementGuid>aaf1e94b-6de5-416a-9bdd-92ab4c767b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAddress&quot;)</value>
      <webElementGuid>68f1d763-fff5-48bc-b5a4-15b215adc664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAddress']</value>
      <webElementGuid>45529c02-5a74-433f-974a-d193a38aa5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/input</value>
      <webElementGuid>bbd0f08a-f6aa-47ab-a6b8-7ce8c0317e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1bf6dadb-0761-4981-a4b2-cf7f70ab2dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAddress' and @placeholder = 'Nama Lengkap']</value>
      <webElementGuid>157433fe-b5c8-42e9-9758-1fc001d201a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
